package com.example.nutricook.view.nav

internal object Routes {
    const val INTRO = "intro"
    const val ONBOARDING = "onboarding"
    const val LOGIN = "login"
    const val REGISTER = "register"

    const val HOME = "home"
    const val CATEGORIES = "categories"
    const val RECIPES = "recipes"
    const val PROFILE = "profile"

    const val RECIPE_DISCOVERY = "recipe_discovery"
    const val RECIPE_DETAIL = "recipe_detail/{recipeTitle}"
    const val INGREDIENTS = "ingredients"
    const val INGREDIENT_DETAIL = "ingredient_detail/{ingredientName}"
    const val INGREDIENT_BROWSER = "ingredient_browser"
    const val NUTRITION_DETAIL = "nutrition_detail"
    const val CREATE_RECIPE = "create_recipe"
    const val UPLOAD_SUCCESS = "upload_success"
    const val RECIPE_DIRECTION = "recipe_direction"
    const val RECIPE_GUIDANCE = "recipe_guidance"
    const val EXERCISE_SUGGESTIONS = "exercise_suggestions"
    const val EXERCISE_DETAIL = "exercise_detail/{exerciseName}/{imageRes}/{duration}/{calories}/{difficulty}"
    const val RECENT_ACTIVITY = "recent_activity"
    const val POSTS = "posts"
    const val EDIT_PROFILE = "edit_profile"
    const val SETTINGS = "settings"
    const val NOTIFICATIONS = "notifications"

    const val RECIPE_INFO = "recipe_info/{recipeTitle}/{imageRes}"
    const val RECIPE_STEP = "recipe_step"
    const val RECIPE_STEP_FINAL = "recipe_step_final"
    const val RECIPE_STEP2 = "recipe_step2"
    const val NUTRITIONFACTS = "nutrition_facts"
    const val REVIEWSCREEN = "review_screen"
    const val ARTICLEDETAIL = "article_detail"
    const val CUSTOM_FOOD_CALCULATOR = "custom_food_calculator"
    const val ADD_MEAL = "add_meal"
}
